spring:
  kafka:
    bootstrap-servers: broker:29092
    consumer:
      group-id: notificationId
      properties:
        spring:
          json:
            type:
              mapping: event:org.techmarket.event.OrderPlacedEvent
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    template:
      default-topic: orderTopic
  mail:
    host: mailhog
    username:
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        url: http://grafana-lgtm:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://grafana-lgtm:4318/v1/traces
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: '1.0'
