management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    health:
      show-details: always
    circuitbreakers:
      enabled: 'true'
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  logging:
    export:
      otlp:
        endpoint: http://localhost:4318/v1/logs
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: '1.0'
spring:
  kafka:
    bootstrap-servers: localhost:29092

    template:
      default-topic: orderTopic

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        # 1. Ignore the producer's class header
        spring.json.use.type.headers: false
        # 2. Force it to deserialize into your consumer's class
        spring.json.value.default.type: "org.techmarket.event"
        spring.json.trusted.packages: "*"
  mail:
    host: localhost
    username: techmarketJP@gmail.com
    port: '1025'
    properties:
      mail:
        transport:
          protocol: smtp
        debug: 'true'
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: Hola1234!
  application:
    name: notification-service
server:
  port: '0'
