spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://product-service:8080
              predicates:
                - Path=/api/product/**

            - id: order-service
              uri: http://order-service:8080
              predicates:
                - Path=/api/order/**

            - id: inventory-service
              uri: http://inventory-service:8080
              predicates:
                - Path=/api/inventory/**,/api/category/**,/api/promotion/**
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/techmarket-realm
          jwk-set-uri: http://keycloak:8080/realms/techmarket-realm/protocol/openid-connect/certs
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        url: http://grafana-lgtm:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://grafana-lgtm:4318/v1/traces
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: '1.0'
test:
  profile: docker-loaded