spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://product-service:8082
              predicates:
                - Path=/api/product/**
              filters:
                - name: RateLimit
                  args:
                    replenishRate: 4
                    burstCapacity: 4
                - name: CircuitBreaker
                  args:
                    name: product-service

            - id: order-service
              uri: http://order-service:8081
              predicates:
                - Path=/api/order/**
              filters:
                - name: RateLimit
                  args:
                    replenishRate: 4
                    burstCapacity: 4
                - name: CircuitBreaker
                  args:
                    name: order-service

            - id: inventory-service
              uri: http://inventory-service:8083
              predicates:
                - Path=/api/inventory/**,/api/category/**,/api/promotion/**
              filters:
                - name: RateLimit
                  args:
                    replenishRate: 4
                    burstCapacity: 4
                - name: CircuitBreaker
                  args:
                    name: inventory-service

            - id: product-service-openapi
              uri: http://product-service:8082
              predicates:
                - Path=/aggregate/product-service/v3/api-docs
              filters:
                - RewritePath=/aggregate/product-service/v3/api-docs, /v3/api-docs

            - id: order-service-openapi
              uri: http://order-service:8081
              predicates:
                - Path=/aggregate/order-service/v3/api-docs
              filters:
                - RewritePath=/aggregate/order-service/v3/api-docs, /v3/api-docs

            - id: inventory-service-openapi
              uri: http://inventory-service:8083
              predicates:
                - Path=/aggregate/inventory-service/v3/api-docs
              filters:
                - RewritePath=/aggregate/inventory-service/v3/api-docs, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Product Service API
        url: /aggregate/product-service/v3/api-docs
      - name: Order Service API
        url: /aggregate/order-service/v3/api-docs
      - name: Inventory Service API
        url: /aggregate/inventory-service/v3/api-docs

  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/techmarket-realm
          jwk-set-uri: http://keycloak:8080/realms/techmarket-realm/protocol/openid-connect/certs
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        url: http://grafana-lgtm:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://grafana-lgtm:4318/v1/traces
  tracing:
    sampling:
      probability: '1.0'

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50.0
        slowCallRateThreshold: 50.0
        slowCallDurationThreshold: 5000
        waitDurationInOpenState: 30000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

    instances:
      product-service:
        baseConfig: default
      order-service:
        baseConfig: default
      inventory-service:
        baseConfig: default
