management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces

  tracing:
    sampling:
      probability: 1.0


spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/techmarket-realm

  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 15000
            response-timeout: 15000
          routes:
            - id: product-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/product/**
              filters:
                - name: RateLimit
                  args:
                    replenishRate: 4
                    burstCapacity: 4
                - name: CircuitBreaker
                  args:
                    name: product-service

            - id: order-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/order/**
              filters:
                - name: RateLimit
                  args:
                    replenishRate: 4
                    burstCapacity: 4
                - name: CircuitBreaker
                  args:
                    name: order-service

            - id: inventory-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/inventory/**,/api/category/**,/api/promotion/**
              filters:
                - name: RateLimit
                  args:
                    replenishRate: 4
                    burstCapacity: 4
                - name: CircuitBreaker
                  args:
                    name: inventory-service

            - id: product-service-openapi
              uri: http://localhost:8082
              predicates:
                - Path=/aggregate/product-service/v3/api-docs
              filters:
                - RewritePath=/aggregate/product-service/v3/api-docs, /v3/api-docs

            - id: order-service-openapi
              uri: http://localhost:8081
              predicates:
                - Path=/aggregate/order-service/v3/api-docs
              filters:
                - RewritePath=/aggregate/order-service/v3/api-docs, /v3/api-docs

            - id: inventory-service-openapi
              uri: http://localhost:8083
              predicates:
                - Path=/aggregate/inventory-service/v3/api-docs
              filters:
                - RewritePath=/aggregate/inventory-service/v3/api-docs, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Product Service API
        url: /aggregate/product-service/v3/api-docs
      - name: Order Service API
        url: /aggregate/order-service/v3/api-docs
      - name: Inventory Service API
        url: /aggregate/inventory-service/v3/api-docs


server:
  port: 8080
  forward-headers-strategy: framework


logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-}, spanId=%X{spanId:-}] %logger{36}"
  level:
    root: INFO
    io.micrometer: DEBUG
    io.opentelemetry: DEBUG


resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50.0
        slowCallRateThreshold: 50.0
        slowCallDurationThreshold: 5000
        waitDurationInOpenState: 30000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.net.ConnectException
          - java.io.IOException
          - java.util.concurrent.TimeoutException

    instances:
      product-service:
        baseConfig: default
        waitDurationInOpenState: 20000

      order-service:
        baseConfig: default
        failureRateThreshold: 60.0
        waitDurationInOpenState: 25000

      inventory-service:
        baseConfig: default
        waitDurationInOpenState: 20000


  ratelimiter:
    configs:
      default:
        registerHealthIndicator: false
        limitForPeriod: 100
        limitRefreshPeriod: 1m
        timeoutDuration: 5s

    instances:
      default:
        baseConfig: default