DROP TABLE IF EXISTS t_inventory;


CREATE TABLE t_inventory (
                                    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
                                    quantity int4 NULL,
                                    sku_code varchar(255) NULL,
                                    CONSTRAINT t_inventory_pkey PRIMARY KEY (id)
);