spring:
  application:
    name: ai-ops-agent
  ai:
    openai:
      base-url: https://openrouter.ai/api/v1
      api-key: ${OPENAI_ROUTER_KEY}
      chat:
        model: qwen/qwen3-8b
        temperature: 0.2
jpmarket:
  services:
    notification:
      base-url: http://localhost:8087
    order:
      base-url: http://localhost:8081
    inventory:
      base-url: http://localhost:8083
    product:
      base-url: http://localhost:8082
    gateway:
      base-url: http://localhost:8084
  prometheus:
    base-url: http://localhost:9090
  github:
    api:
      url: https://api.github.com
      token: ${GITHUB_TOKEN}
      owner: juliparodi
      repo: Backend-JP-Market