spring:
  kafka:
    bootstrap-servers: broker:29092
  datasource:
    url: jdbc:mysql://mysql-order:3306/order-service
    username: juliparodi
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  application:
    name: order-service
inventory:
  url: http://inventory-service:8083/api/inventory


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        url: http://grafana-lgtm:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://grafana-lgtm:4318/v1/traces
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: '1.0'

logging:
  level:
    root: INFO
    com.techmarket: DEBUG