management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    health:
      show-details: always
    circuitbreakers:
      enabled: 'true'
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  logging:
    export:
      otlp:
        endpoint: http://localhost:4318/v1/logs
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: '1.0'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: juliparodi
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-service
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.techmarket.orderservice.event.OrderPlacedEvent
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: orderTopic
    bootstrap-servers: localhost:29092
  flyway:
    enabled: true
    locations: classpath:db
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        failureRateThreshold: '50'
        permittedNumberOfCallsInHalfOpenState: '3'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: '5'
  timelimiter:
    instances:
      inventory:
        base-config: default
        timeout-duration: 10s
        cancel-running-future: 'true'
    configs:
      default:
        timeout-duration: 10s
  retry:
    instances:
      inventory:
        max-attempts: '3'
        wait-duration: 12s
server:
  port: '8081'
inventory:
  url: http://inventory-service:8082/api/techMarket/inventory
