spring:
  mongodb:
    host: mongo
    port: 27017
    database: product-service
    username: julianparodi19
    password: ${MONGO_JULIP_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        url: http://grafana-lgtm:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://grafana-lgtm:4318/v1/traces
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: '1.0'

logging:
  level:
    root: INFO
    com.techmarket: DEBUG