management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    health:
      show-details: always
    circuitbreakers:
      enabled: 'true'
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  logging:
    export:
      otlp:
        endpoint: http://localhost:4318/v1/logs
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: '1.0'
pathJson: src/test/resources/json/
spring:
  mongodb:
    uri: mongodb+srv://julianparodi19:${MONGO_PASSWORD}@jpmarket.djj41xn.mongodb.net/jpmarket?retryWrites=true&w=majority&sslVerifyCertificate=false
  application:
    name: product-service
server:
  port: '0'
