server.port=8080
spring.datasource.url=jdbc:postgresql://postgres:5431/inventory-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=juliparodi
spring.datasource.password=${POSTGRE_PASSWORD}
spring.kafka.bootstrap-servers=broker:29092

#spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.locations=classpath:db
spring.flyway.enabled=true