spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: juliparodi
    url: jdbc:postgresql://postgres-inventory:5431/inventory-service
    password: ${POSTGRE_PASSWORD}
  flyway:
    enabled: 'true'
    locations: classpath:db
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      properties:
        schema.registry.url: http://schema-registry:8086
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        url: http://grafana-lgtm:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://grafana-lgtm:4318/v1/traces
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: '1.0'