spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: avnadmin
    url: jdbc:postgresql://inventory-service-juliparodi26.a.aivencloud.com:21097/defaultdb?user=avnadmin&password=${POSTGRE_PASSWORD}
    password: ${POSTGRE_PASSWORD}
  flyway:
    enabled: 'true'
    locations: classpath:db
  application:
    name: inventory-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    health:
      show-details: always
    circuitbreakers:
      enabled: 'true'
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  logging:
    export:
      otlp:
        endpoint: http://localhost:4318/v1/logs
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: '1.0'
server:
  port: '0'
