spring:
  kafka:
    template:
      default-topic: orderTopic
    consumer:
      auto-offset-reset: earliest
      group-id: inventory-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        specific.avro.reader: true
    bootstrap-servers: localhost:29092
  datasource:
    driver-class-name: org.postgresql.Driver
    username: juliparodi
    url: jdbc:postgresql://localhost:5431/inventory-service
    password: ${POSTGRE_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db
  application:
    name: inventory-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    health:
      show-details: always
    circuitbreakers:
      enabled: 'true'
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: '1.0'
server:
  port: '8083'
logging:
  level:
    root: INFO
    com.techmarket: DEBUG
