#DB
spring.datasource.url=jdbc:postgresql://inventory-service-juliparodi26.a.aivencloud.com:21097/defaultdb?user=avnadmin&password=${POSTGRE_PASSWORD}
spring.datasource.username=avnadmin
spring.datasource.password=${POSTGRE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.locations=classpath:db
spring.flyway.enabled=true

#APP
spring.application.name=inventory-service
server.port=0


#actuator
management.endpoints.web.exposure.include=prometheus